FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install streamlit scikit-learn

COPY dashboard/movie_dashboard.py .

EXPOSE 8501
CMD ["streamlit", "run", "movie_dashboard.py", "--server.address=0.0.0.0"]